### PR TITLE
Fix boot dependency and hook get-version

### PR DESCRIPTION
**Pull request by arichiardi**

### CODE REVIEW

**Comment by burn2delete** [comment]
@arichiardi I dont see what this intends to fix. Boot-semver replaces the need for bootlaces.

**Comment by arichiardi** [comment]
Ops Sorry I was playing with bootlaces but meant to take it away from the PR...will do it. It is kind of cleaning up stuff in general (you don't need to depend on boot.core if it is in `boot.properties` and the version has not been released yet). Feel free to dismiss it however, I needed it in order to build locally...

**Comment by arichiardi** [comment]
I tried to remove `:version` from the `pom` task but:

```
                              java.lang.Thread.run              Thread.java:  748
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 2020
                                 boot.core/boot/fn                 core.clj: 1031
                               boot.core/run-tasks                 core.clj: 1021
        degree9.boot-semver.impl/eval1347/fn/fn/fn                 impl.clj:  139
       java.lang.Exception: Project and Version are needed to create pom.xml
clojure.lang.ExceptionInfo: Project and Version are needed to create pom.xml
    line: 78
```

**Comment by burn2delete** [comment]
Closing as I dont believe there is anything to fix here - make sure you are using the tasks from this library and not the built-in ones.

**Pull request closed without merging**
